// This file is auto-generated by tauri-specta. Do not edit manually.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listProjects() : Promise<Result<ProjectDiscovery[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveProject() : Promise<Result<ProjectInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveProject(path: string) : Promise<Result<ProjectInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens a folder picker. If the chosen directory has no .ship, initialises one.
 * Sets the result as the active project.
 */
async pickAndOpenProject() : Promise<Result<ProjectInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_and_open_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new project by picking a folder and initializing .ship
 */
async createNewProject() : Promise<Result<ProjectInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_new_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens a folder picker and returns the selected directory path.
 */
async pickProjectDirectory() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_project_directory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates (or initializes) a project from explicit onboarding options.
 */
async createProjectWithOptions(directory: string, name: string | null, description: string | null, config: ProjectConfig | null) : Promise<Result<ProjectInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project_with_options", { directory, name, description, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Auto-detect current project from the working directory (for dogfooding).
 */
async detectCurrentProject() : Promise<Result<ProjectInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_current_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listItems() : Promise<Result<IssueEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_items") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIssueByPath(path: string) : Promise<Result<Issue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_issue_by_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNewIssue(title: string, description: string, status: string, assignee: string | null, tags: string[] | null) : Promise<Result<IssueEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_new_issue", { title, description, status, assignee, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateIssueByPath(path: string, issue: Issue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_issue_by_path", { path, issue }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveIssueStatus(fileName: string, fromStatus: string, toStatus: string) : Promise<Result<IssueEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_issue_status", { fileName, fromStatus, toStatus }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteIssueByPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_issue_by_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAdrsCmd() : Promise<Result<AdrEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_adrs_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNewAdr(title: string, decision: string) : Promise<Result<AdrEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_new_adr", { title, decision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAdrCmd(fileName: string) : Promise<Result<AdrEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_adr_cmd", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAdrCmd(fileName: string, adr: ADR) : Promise<Result<AdrEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_adr_cmd", { fileName, adr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAdrCmd(fileName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_adr_cmd", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSpecsCmd() : Promise<Result<SpecInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_specs_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSpecCmd(fileName: string) : Promise<Result<SpecDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_spec_cmd", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSpecCmd(title: string, content: string) : Promise<Result<SpecDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_spec_cmd", { title, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSpecCmd(fileName: string, content: string) : Promise<Result<SpecDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_spec_cmd", { fileName, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSpecCmd(fileName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_spec_cmd", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLog() : Promise<Result<LogEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<ProjectConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProjectConfig() : Promise<Result<ProjectConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProjectConfig(config: ProjectConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAppSettings(config: ProjectConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_app_settings", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ADR = { metadata: AdrMetadata; body: string }
export type AdrEntry = { file_name: string; path: string; adr: ADR }
export type AdrMetadata = { id?: string; title: string; status: string; date: string; tags?: string[]; spec?: string | null }
/**
 * Configuration for the AI pass-through CLI.
 * Ship does not call any AI APIs directly — it spawns the configured CLI binary.
 * Supported providers: "claude" (Claude Code CLI), "gemini", "codex".
 */
export type AiConfig = { 
/**
 * Which AI CLI to use. Defaults to "claude".
 */
provider: string | null; 
/**
 * Override the binary path if it's not on PATH. Defaults to the provider name.
 */
cli_path: string | null }
/**
 * Controls which parts of .ship/ are committed to git.
 */
export type GitConfig = { 
/**
 * Paths/globs that should be gitignored (relative to .ship/).
 */
ignore?: string[]; 
/**
 * Paths/globs that should be committed (relative to .ship/).
 */
commit?: string[] }
export type Issue = ({ id?: string; title: string; created: string; updated: string; assignee?: string | null; tags?: string[]; spec?: string | null; links?: IssueLink[] }) & { description: string }
export type IssueEntry = { file_name: string; status: string; path: string; issue: Issue }
/**
 * A typed link between issues or to external resources.
 */
export type IssueLink = { type: string; target: string }
export type LogEntry = { timestamp: string; actor: string; action: string; details: string }
export type ProjectConfig = { version?: string; name: string | null; description: string | null; statuses?: StatusConfig[]; git?: GitConfig; ai: AiConfig | null }
export type ProjectDiscovery = { name: string; 
/**
 * Stored as PathBuf internally; serialized as a string path on the wire.
 */
path: string; issue_count?: number }
export type ProjectInfo = { name: string; path: string; issue_count: number }
export type SpecDocument = { file_name: string; title: string; path: string; content: string }
export type SpecInfo = { file_name: string; title: string; path: string }
export type StatusConfig = { id: string; name: string; color?: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
